#!/bin/bash

# ProxmoxVE Debian VM Creation Script
# Usage: ./install.sh [OPTIONS] <project_directory> <target_node>
# Example: ./install.sh --mem=4G --disk=40G --cpus=4 pve-debian-vm tango.ank.com

set -e

# Set default values
DEFAULT_MEMORY=2048  # MB
DEFAULT_CPU_CORES=2
DEFAULT_DISK_SIZE=20  # GB

# Initialize variables
MEMORY_MB="$DEFAULT_MEMORY"
CPU_CORES="$DEFAULT_CPU_CORES"
DISK_SIZE_GB="$DEFAULT_DISK_SIZE"
DRY_RUN=false
HOSTNAME=""
VM_IP=""
USE_STATIC_IP=false
CONSOLE_PASSWORD="debian" # Default console password

# Function to convert memory units to MB
convert_memory_to_mb() {
    local mem_str="$1"
    if [[ "$mem_str" =~ ^([0-9]+)([GgMm]?)$ ]]; then
        local value="${BASH_REMATCH[1]}"
        local unit="${BASH_REMATCH[2]}"
        
        # Convert unit to lowercase
        unit=$(echo "$unit" | tr '[:upper:]' '[:lower:]')
        
        case "$unit" in
            "g")
                echo $((value * 1024))
                ;;
            "m"|"")
                echo "$value"
                ;;
            *)
                echo "Error: Invalid memory unit '$unit'. Use G for gigabytes or M for megabytes." >&2
                return 1
                ;;
        esac
    else
        echo "Error: Invalid memory format '$mem_str'. Use format like '4G' or '2048M'." >&2
        return 1
    fi
}

# Function to generate human-readable configuration summary
generate_config_summary() {
    local vars_file="vars.yml"  # We're already in the project directory
    
    echo ""
    echo "=========================================="
    echo "📋 CONFIGURATION SUMMARY"
    echo "=========================================="
    
    # Extract values from vars.yml using awk (more reliable parsing)
    local vm_storage=$(awk -F': *' '/^vm_storage:/ {gsub(/[" ]/, "", $2); print $2}' "$vars_file")
    local vm_network_bridge=$(awk -F': *' '/^vm_network_bridge:/ {gsub(/[" ]/, "", $2); print $2}' "$vars_file")
    local vm_cpu_type=$(awk -F': *' '/^vm_cpu_type:/ {gsub(/[" ]/, "", $2); print $2}' "$vars_file")
    local vm_disk_format=$(awk -F': *' '/^vm_disk_format:/ {gsub(/[" ]/, "", $2); print $2}' "$vars_file")
    
    # Display VM configuration
    echo "🖥️  VM Configuration:"
    if [ -n "$HOSTNAME" ]; then
        echo "   Name: $VM_SHORT_NAME"
        echo "   FQDN: $HOSTNAME"
    else
        echo "   Name: debian-vm-<timestamp>"
        echo "   FQDN: debian-vm.ank.com"
    fi
    echo "   Memory: ${MEMORY_MB}MB"
    echo "   CPU Cores: $CPU_CORES"
    echo "   CPU Type: $vm_cpu_type"
    echo "   Disk Size: ${DISK_SIZE_GB}GB ($vm_disk_format format)"
    echo ""
    
    # Display network configuration
    echo "🌐 Network Configuration:"
    if [ "$USE_STATIC_IP" = true ]; then
        echo "   Type: Static IP"
        echo "   IP Address: $VM_IP"
        echo "   Gateway: 10.0.42.1"
        echo "   Netmask: 255.255.255.0"
        echo "   DNS: 10.0.42.1"
    else
        echo "   Type: DHCP (automatic)"
        if [ -n "$HOSTNAME" ]; then
            echo "   Reason: Hostname '$HOSTNAME' did not resolve to IP"
        else
            echo "   Reason: No hostname specified"
        fi
    fi
    echo "   Bridge: $vm_network_bridge"
    echo ""
    
    # Display Proxmox configuration
    echo "🏗️  Proxmox Configuration:"
    echo "   Target Node: $TARGET_NODE"
    echo "   Storage Pool: $vm_storage"
    echo "   VM ID: <auto-generated>"
    echo ""
    
    # Display security configuration
    echo "🔐 Security Configuration:"
    echo "   SSH Key Auth: ✅ Enabled (Ed25519)"
    echo "   Password Auth: ❌ Disabled"
    echo "   Root SSH: ✅ Enabled (key-only)"
    echo "   User Account: debian (key-only)"
    echo "   User Password: $CONSOLE_PASSWORD (console login only)"
    echo ""
    
    # Display installation details
    echo "📦 Installation Details:"
    echo "   OS: Debian (latest available ISO)"
    echo "   Packages: openssh-server, curl, wget, vim, net-tools, qemu-guest-agent"
    echo "   Timezone: UTC"
    echo "   Locale: en_US"
    echo ""
    
    # Display next steps
    echo "🚀 After Installation:"
    echo "   1. Installation time: ~10-15 minutes"
    echo "   2. Find VM IP: ./find-vm-ip.sh <vm-name> $TARGET_NODE"
    if [ -n "$HOSTNAME" ] && [ "$USE_STATIC_IP" = true ]; then
        echo "   3. SSH access: ssh root@$VM_IP (or ssh debian@$VM_IP)"
    else
        echo "   3. SSH access: ssh root@<vm-ip> (or ssh debian@<vm-ip>)"
    fi
    echo "   4. Monitor: ProxmoxVE web interface"
    echo "=========================================="
}

# Function to resolve hostname to IP address
resolve_hostname() {
    local hostname="$1"
    local ip_address
    
    echo "Looking up IP address for hostname: $hostname" >&2
    
    # Try to resolve the hostname using dig first (more reliable)
    if command -v dig &> /dev/null; then
        ip_address=$(dig +short "$hostname" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
    fi
    
    # Fallback to nslookup if dig failed or not available
    if [ -z "$ip_address" ] && command -v nslookup &> /dev/null; then
        ip_address=$(nslookup "$hostname" 2>/dev/null | awk '/^Address: / { print $2 }' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
    fi
    
    # Fallback to host command
    if [ -z "$ip_address" ] && command -v host &> /dev/null; then
        ip_address=$(host "$hostname" 2>/dev/null | awk '/has address/ { print $4 }' | head -1)
    fi
    
    if [ -n "$ip_address" ]; then
        echo "Found IP address: $ip_address" >&2
        echo "$ip_address"
        return 0
    else
        echo "Could not resolve hostname: $hostname" >&2
        return 1
    fi
}
convert_disk_to_gb() {
    local disk_str="$1"
    if [[ "$disk_str" =~ ^([0-9]+)([GgTt]?)$ ]]; then
        local value="${BASH_REMATCH[1]}"
        local unit="${BASH_REMATCH[2]}"
        
        # Convert unit to lowercase
        unit=$(echo "$unit" | tr '[:upper:]' '[:lower:]')
        
        case "$unit" in
            "g"|"")
                echo "$value"
                ;;
            "t")
                echo $((value * 1024))
                ;;
            *)
                echo "Error: Invalid disk unit '$unit'. Use G for gigabytes or T for terabytes." >&2
                return 1
                ;;
        esac
    else
        echo "Error: Invalid disk format '$disk_str'. Use format like '100G' or '2T'." >&2
        return 1
    fi
}

# Function to hash passwords for preseed
hash_password() {
    local password="$1"
    # Use mkpasswd if available, otherwise use openssl
    if command -v mkpasswd >/dev/null 2>&1; then
        mkpasswd --method=sha-512 "$password"
    else
        openssl passwd -6 "$password"
    fi
}

# Function to show usage
show_usage() {
    echo "Usage: $0 [OPTIONS] <project_directory> <target_node>"
    echo "Example: $0 --hostname=jinx.ank.com --mem=4G --disk=40G --cpus=4 --password=mypassword pve-debian-vm tango.ank.com"
    echo ""
    echo "Options:"
    echo "  --hostname=NAME   VM hostname (e.g., jinx.ank.com)"
    echo "                    If hostname resolves to IP, static network config will be used"
    echo "                    If hostname doesn't resolve, DHCP will be used"
    echo "  --mem=SIZE        Memory size (default: ${DEFAULT_MEMORY}M)"
    echo "                    Examples: --mem=4G, --mem=2048M"
    echo "  --disk=SIZE       Disk size (default: ${DEFAULT_DISK_SIZE}G)"
    echo "                    Examples: --disk=100G, --disk=2T"
    echo "  --cpus=N          Number of CPU cores (default: $DEFAULT_CPU_CORES)"
    echo "                    Examples: --cpus=4, --cpus=8"
    echo "  --password=PASS   Console password for debian user (default: debian)"
    echo "                    Used for console login when SSH is not available"
    echo "  --dry-run         Show what would be done without executing"
    echo "  -h, --help        Show this help message"
    echo ""
    echo "Network Configuration:"
    echo "  Static IP: Gateway 10.0.42.1, Netmask 255.255.255.0"
    echo "  DHCP: Automatic configuration when hostname doesn't resolve"
    echo ""
    echo "Parameters:"
    echo "  project_directory Directory containing Ansible playbooks"
    echo "  target_node       Proxmox node to create VM on"
    echo ""
    echo "Available nodes:"
    echo "  - tango.ank.com"
    echo "  - victor.ank.com"  
    echo "  - xray.ank.com"
}

# Parse command line arguments
POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
        --hostname=*)
            HOSTNAME="${1#*=}"
            if [ -z "$HOSTNAME" ]; then
                echo "Error: Hostname cannot be empty" >&2
                exit 1
            fi
            shift
            ;;
        --mem=*)
            MEMORY_STR="${1#*=}"
            MEMORY_MB=$(convert_memory_to_mb "$MEMORY_STR")
            if [ $? -ne 0 ]; then exit 1; fi
            shift
            ;;
        --disk=*)
            DISK_STR="${1#*=}"
            DISK_SIZE_GB=$(convert_disk_to_gb "$DISK_STR")
            if [ $? -ne 0 ]; then exit 1; fi
            shift
            ;;
        --cpus=*)
            CPU_CORES="${1#*=}"
            if ! [[ "$CPU_CORES" =~ ^[1-9][0-9]*$ ]]; then
                echo "Error: CPU cores must be a positive integer" >&2
                exit 1
            fi
            shift
            ;;
        --password=*)
            CONSOLE_PASSWORD="${1#*=}"
            if [ -z "$CONSOLE_PASSWORD" ]; then
                echo "Error: Password cannot be empty" >&2
                exit 1
            fi
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        --*)
            echo "Error: Unknown option $1" >&2
            show_usage
            exit 1
            ;;
        *)
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
    esac
done

# Restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

# Check if we have the required positional arguments
if [ $# -ne 2 ]; then
    echo "Error: Missing required arguments" >&2
    show_usage
    exit 1
fi

PROJECT_DIR="$1"
TARGET_NODE="$2"

# Validate project directory exists
if [ ! -d "$PROJECT_DIR" ]; then
    echo "Error: Project directory '$PROJECT_DIR' does not exist"
    exit 1
fi

# Validate target node
case "$TARGET_NODE" in
    "tango.ank.com"|"victor.ank.com"|"xray.ank.com")
        echo "Creating VM on node: $TARGET_NODE"
        ;;
    *)
        echo "Error: Invalid target node '$TARGET_NODE'"
        echo "Valid nodes are: tango.ank.com, victor.ank.com, xray.ank.com"
        exit 1
        ;;
esac

# Check if ansible is installed
if ! command -v ansible-playbook &> /dev/null; then
    echo "Error: ansible-playbook command not found"
    echo "Please install Ansible first:"
    echo "  brew install ansible"
    exit 1
fi

# Check if SSH key exists
if [ ! -f ~/.ssh/id_ed25519 ]; then
    echo "Error: SSH private key not found at ~/.ssh/id_ed25519"
    exit 1
fi

# Check if required files exist in project directory
REQUIRED_FILES=("inventory.yml" "create-vm.yml" "vars.yml" "preseed.cfg.j2" "ansible.cfg")
for file in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$PROJECT_DIR/$file" ]; then
        echo "Error: Required file '$file' not found in '$PROJECT_DIR'"
        exit 1
    fi
done

# Process hostname if provided
if [ -n "$HOSTNAME" ]; then
    echo "Processing hostname: $HOSTNAME"
    
    # Try to resolve the hostname to an IP address
    if VM_IP=$(resolve_hostname "$HOSTNAME"); then
        USE_STATIC_IP=true
        echo "Will use static IP configuration: $VM_IP"
        echo "Gateway: 10.0.42.1, Netmask: 255.255.255.0"
    else
        USE_STATIC_IP=false
        echo "Hostname did not resolve - will use DHCP configuration"
        VM_IP=""
    fi
    
    # Extract short hostname (everything before first dot)
    VM_SHORT_NAME=$(echo "$HOSTNAME" | cut -d'.' -f1)
else
    echo "No hostname specified - will use default hostname 'debian-vm'"
    VM_SHORT_NAME="debian-vm"
    USE_STATIC_IP=false
    VM_IP=""
fi

# Change to project directory
cd "$PROJECT_DIR"

if [ "$DRY_RUN" = true ]; then
    echo "========================================"
    echo "DRY RUN - ProxmoxVE Debian VM Creation"
    echo "========================================"
else
    echo "========================================"
    echo "ProxmoxVE Debian VM Creation"
    echo "========================================"
fi

echo "Project Directory: $PROJECT_DIR"
echo "Target Node: $TARGET_NODE"
if [ -n "$HOSTNAME" ]; then
    echo "Hostname: $HOSTNAME"
    if [ "$USE_STATIC_IP" = true ]; then
        echo "Network: Static IP ($VM_IP)"
        echo "Gateway: 10.0.42.1, Netmask: 255.255.255.0"
    else
        echo "Network: DHCP (hostname did not resolve)"
    fi
else
    echo "Hostname: debian-vm (default)"
    echo "Network: DHCP (default)"
fi
echo "Memory: ${MEMORY_MB}MB"
echo "CPU Cores: $CPU_CORES"
echo "Disk Size: ${DISK_SIZE_GB}GB"
echo "Timestamp: $(date)"

# Generate password hash for preseed
CONSOLE_PASSWORD_HASH=$(hash_password "$CONSOLE_PASSWORD")
if [ -z "$CONSOLE_PASSWORD_HASH" ]; then
    echo "Error: Failed to generate password hash" >&2
    exit 1
fi

if [ "$DRY_RUN" = true ]; then
    echo ""
    echo "Generating VM configuration preview..."
    
    # Use Ansible to show what the configuration would be without executing VM creation
    ansible-playbook create-vm.yml \
        --extra-vars "target_host=$TARGET_NODE" \
        --extra-vars "vm_memory=$MEMORY_MB" \
        --extra-vars "vm_cores=$CPU_CORES" \
        --extra-vars "vm_disk_size=$DISK_SIZE_GB" \
        --extra-vars "vm_hostname=$VM_SHORT_NAME" \
        --extra-vars "vm_fqdn=$HOSTNAME" \
        --extra-vars "vm_static_ip=$VM_IP" \
        --extra-vars "vm_use_static_ip=$USE_STATIC_IP" \
        --extra-vars "console_password_hash=$CONSOLE_PASSWORD_HASH" \
        --extra-vars "dry_run_mode=true" \
        --limit "$TARGET_NODE" \
        --check \
        -v
    
    echo ""
    echo "This is a dry run - no VM will be created."
    echo "Remove --dry-run to execute the actual deployment."
    
    # Generate human-readable configuration summary
    generate_config_summary
else
    echo "========================================"
    
    # Run the Ansible playbook
    echo "Running Ansible playbook..."
    ansible-playbook create-vm.yml \
        --extra-vars "target_host=$TARGET_NODE" \
        --extra-vars "vm_memory=$MEMORY_MB" \
        --extra-vars "vm_cores=$CPU_CORES" \
        --extra-vars "vm_disk_size=$DISK_SIZE_GB" \
        --extra-vars "vm_hostname=$VM_SHORT_NAME" \
        --extra-vars "vm_fqdn=$HOSTNAME" \
        --extra-vars "vm_static_ip=$VM_IP" \
        --extra-vars "vm_use_static_ip=$USE_STATIC_IP" \
        --extra-vars "console_password_hash=$CONSOLE_PASSWORD_HASH" \
        --limit "$TARGET_NODE" \
        -v
fi

if [ "$DRY_RUN" = false ]; then
    echo "========================================"
    echo "VM creation process completed!"
    echo "========================================"
    echo ""
    echo "Next steps:"
    echo "1. The VM is now installing Debian automatically"
    echo "2. Installation will take approximately 10-15 minutes"
    echo "3. You can monitor progress in the ProxmoxVE web interface"
    echo "4. Once complete, find the VM IP address:"
    echo "   ./find-vm-ip.sh <vm-name> $TARGET_NODE"
    echo "5. Then SSH to the VM using your SSH key:"
    echo "   ssh root@<vm-ip>"
    echo "   ssh debian@<vm-ip>"
    echo ""
    echo "Quick commands:"
    echo "  Check VM status: ssh root@$TARGET_NODE 'qm list'"
    echo "  Find VM IP:      ./find-vm-ip.sh \$(ssh root@$TARGET_NODE 'qm list | tail -1 | awk \"{print \\$2}\"') $TARGET_NODE"
    echo ""
    echo "Note: SSH password authentication is disabled for security"
fi